"""empty message

Revision ID: 304f72905531
Revises: af5e47d41e39
Create Date: 2023-04-08 15:26:43.247346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '304f72905531'
down_revision = 'af5e47d41e39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('senha', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nome')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    # ### end Alembic commands ###
