"""empty message

Revision ID: 5f915d9d6881
Revises: c08ad74b9583
Create Date: 2023-05-20 18:01:18.518918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f915d9d6881'
down_revision = 'c08ad74b9583'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('cpf',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=14),
               existing_nullable=True)
        batch_op.alter_column('celular',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=15),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('celular',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=11),
               existing_nullable=True)
        batch_op.alter_column('cpf',
               existing_type=sa.String(length=14),
               type_=sa.VARCHAR(length=11),
               existing_nullable=True)

    # ### end Alembic commands ###
