"""empty message

Revision ID: 6998aa37ced8
Revises: e89e77ea650c
Create Date: 2023-05-21 14:34:20.206895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6998aa37ced8'
down_revision = 'e89e77ea650c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carro', schema=None) as batch_op:
        batch_op.alter_column('descricao_imagem',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carro', schema=None) as batch_op:
        batch_op.alter_column('descricao_imagem',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
