"""empty message

Revision ID: 8f8930abc031
Revises: f2118a50c0ae
Create Date: 2023-04-29 19:37:45.841092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f8930abc031'
down_revision = 'f2118a50c0ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marca', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('custo_diario', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('capacidade_pessoas', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('quantidade_alugueis', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('data_de_insercao', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carro', schema=None) as batch_op:
        batch_op.drop_column('data_de_insercao')
        batch_op.drop_column('quantidade_alugueis')
        batch_op.drop_column('capacidade_pessoas')
        batch_op.drop_column('custo_diario')
        batch_op.drop_column('marca')

    # ### end Alembic commands ###
