"""empty message

Revision ID: b5a7c676e36a
Revises: a2f8a442edb1
Create Date: 2023-04-16 20:53:15.889465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5a7c676e36a'
down_revision = 'a2f8a442edb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('page_url', sa.String(length=80), nullable=False))
        batch_op.create_unique_constraint(None, ['page_url'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('page_url')

    # ### end Alembic commands ###
