"""empty message

Revision ID: c08ad74b9583
Revises: 790326720306
Create Date: 2023-05-20 17:42:10.884368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c08ad74b9583'
down_revision = '790326720306'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aluguel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_pagar', sa.Numeric(precision=10, scale=2), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpf', sa.String(length=11), nullable=True))
        batch_op.add_column(sa.Column('celular', sa.String(length=11), nullable=True))
        batch_op.add_column(sa.Column('data_cadastro', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['celular'])
        batch_op.create_unique_constraint(None, ['cpf'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('data_cadastro')
        batch_op.drop_column('celular')
        batch_op.drop_column('cpf')

    with op.batch_alter_table('aluguel', schema=None) as batch_op:
        batch_op.drop_column('total_pagar')

    # ### end Alembic commands ###
