"""Aumentando limite das colunas de valor monetário

Revision ID: cb1009a87b04
Revises: 098195468854
Create Date: 2023-05-22 13:17:50.671994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb1009a87b04'
down_revision = '098195468854'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aluguel', schema=None) as batch_op:
        batch_op.alter_column('total_pagar',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=19, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('carro', schema=None) as batch_op:
        batch_op.alter_column('custo_diario',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=19, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carro', schema=None) as batch_op:
        batch_op.alter_column('custo_diario',
               existing_type=sa.Numeric(precision=19, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('aluguel', schema=None) as batch_op:
        batch_op.alter_column('total_pagar',
               existing_type=sa.Numeric(precision=19, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###
