"""empty message

Revision ID: ce9e5180c5c6
Revises: ce3915e4f92d
Create Date: 2023-05-20 19:38:23.898988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce9e5180c5c6'
down_revision = 'ce3915e4f92d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aluguel', schema=None) as batch_op:
        batch_op.drop_constraint('aluguel_carro_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('aluguel_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('carro_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aluguel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('carro_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('aluguel_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('aluguel_carro_id_fkey', 'carro', ['carro_id'], ['id'])

    # ### end Alembic commands ###
