"""empty message

Revision ID: cea4fdeb959c
Revises: 304f72905531
Create Date: 2023-04-12 20:52:34.730047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cea4fdeb959c'
down_revision = '304f72905531'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(length=8), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('placa')
    )
    op.create_table('aluguel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inicio_aluguel', sa.DateTime(), nullable=False),
    sa.Column('final_aluguel', sa.DateTime(), nullable=False),
    sa.Column('carro_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['carro_id'], ['carro.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aluguel')
    op.drop_table('carro')
    # ### end Alembic commands ###
