"""empty message

Revision ID: f8f99e65d8ba
Revises: e34613ad4a62
Create Date: 2023-04-29 19:42:27.906551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8f99e65d8ba'
down_revision = 'e34613ad4a62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marca', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('capacidade_pessoas', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('quantidade_alugueis', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('data_de_insercao', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carro', schema=None) as batch_op:
        batch_op.drop_column('data_de_insercao')
        batch_op.drop_column('quantidade_alugueis')
        batch_op.drop_column('capacidade_pessoas')
        batch_op.drop_column('marca')

    # ### end Alembic commands ###
